testing_mode = false
payment_provider = "stripe" 

stripe_api_key = "stripe_api_key" 

stripe_link = "stripe_link"  


client_id = "Google_client_id you can get by using google auth2"
client_secret = "Google_client_secret you can get by using google auth2"

redirect_url = 'http://localhost:8501/'
